### PR TITLE
Add myBTCcoin Pool

### PR DESCRIPTION
**Pull request by guruinternetservices**
Adding "myBTCcoin Pool" at mybtccoin.com that just found BLOCK #361937. Thank you.

### CODE REVIEW

**Comment by guruinternetservices** [comment]
Did I do this correctly? Just checking when this change is going to be committed. Thank you.

**Comment by jameshilliard** [comment]
Looks fine to me, blockchain.info is usually quite slow when it comes to merging pull requests, can take over a month sometimes.

**Comment by guruinternetservices** [comment]
OK, cool. Thanks for the quick reply!

**Comment by guruinternetservices** [comment]
And thanks for the quick merge after the inquiry!

**Pull request merged**
