### PR TITLE
add pool operated by shawnp0wers

### PR DESCRIPTION
**Pull request by jameshilliard**
Last block found https://blockchain.info/tx/50244248963a3f580e3953819db37a50607e1964b035c2821a25b329696c12cc

Only operator of the pool is known.

### CODE REVIEW

**Comment by alecalve** [comment]
Merging the Bitcoin India PR broke this one. :(

**Comment by jameshilliard** [comment]
@alecalve merge conflicts should be fixed

**Comment by alecalve** [comment]
My Google-fu skills cannot find any link between [18HEMWFXM9UGPVZHUMdBPD3CMFWYn2NPRX](https://blockchain.info/address/18HEMWFXM9UGPVZHUMdBPD3CMFWYn2NPRX) and shawnp0wers. How do you know it's his activity?

**Comment by jameshilliard** [comment]
IRC

**Comment by alecalve** [comment]
Thanks once again.

**Pull request merged**
