### PR TITLE
Rename eSited pool to Hotpool

### PR DESCRIPTION
**Pull request by nullivex**
The original entry here involved some testing. This is a more proper definition of what the pool is.

### CODE REVIEW

**Comment by jameshilliard** [comment]
@nullivex If you are the admin for this pool I would suggest changing the default coinbase sig for this pool from the default "/nodeStratum/" to something that identifies it properly so that we don't have to use the generation address for detection. The url http://hotpool.co/ does not appear to be functional.

**Comment by nullivex** [comment]
@jameshilliard Thank you for the info. I will sort out how to change that string.

I just registered the domain I will update this ticket when it is operational.

Yes I do admin this pool.

**Comment by nullivex** [comment]
@jameshilliard I have changed the stratum client string to `HotPool`

The website is also now online.

Thanks

**Comment by tuzzolo** [comment]
@nullivex https is preferable if your site supports it.

**Comment by jameshilliard** [comment]
@nullivex you should update your pull request with the coinbase sig detection as well

**Comment by nullivex** [comment]
@tuzzolo upgraded to SSL

@jameshilliard added the coinbase sig too

**Comment by tuzzolo** [comment]
Thanks.

**Pull request merged**
