### PR TITLE
2018-05-24 添加haominer矿池

### PR DESCRIPTION
**Pull request by bibodeng**

### CODE REVIEW

**Comment by alecalve** [comment]
Do you have an example of a block mined by the pool?

**Comment by bibodeng** [comment]
not yet, but we used to mine block use other signature, such as Helix([this block](https://btc.com/000000000000000000409dc830656ae8f5d17177b7ac5c770173e476b016bf12)).

**Comment by bibodeng** [comment]
today or tomorrow will have a block of haominer.

**Comment by alecalve** [comment]
You should put your modifications in the `coinbase_tags` object in the JSON file. You put them in the payout addresses but the key is your tag not address.

**Comment by bibodeng** [comment]
oh, I place wrong place, now fixed.

**Comment by alecalve** [comment]
Thanks!

**Pull request merged**
