### PR TITLE
Various Fixes, Cleanup, and Additions

### PR DESCRIPTION
**Pull request by HeroCC**
See commits for details

### CODE REVIEW

**Comment by HeroCC** [comment]
Should I keep this PR open, or is it stale?

**Comment by tuzzolo** [comment]
Yeah it won't auto-merge at this point. Changes look good though. Will merge if you can bring it up to date.

**Comment by HeroCC** [comment]
OK, I will see what I can do!

**Comment by HeroCC** [comment]
Fixed! Let me know what you think

**Comment by rubensayshi** [comment]
1MimPd6LrPKGftPRHWdfk8S3KYBfN4ELnD is digitalBTC afak (http://db.high.re:8080/)

**Comment by rubensayshi** [comment]
and 1BwZeHJo7b7M2op7VDfYnsmcpXsUYEcVHm BTC Nuggets (http://104.197.8.250/)

**Pull request closed without merging**
