### PR TITLE
Update pools.json

### PR DESCRIPTION
**Pull request by jiagengliu**
These miner addresses are labeled unknown but they either sent reward together with other Poolin addresses and/or send to the Poolin reward distributors (39XpoaixBAbUZzaq7g73tmvogBw6rGv8JP, 3QaQ33KSoPVYmZtfTNe6mXt5R3jGgRTjXZ, and 3Dm9H3Z6gChqctoTo5DSN9B9Eyo2kckWm4). Please review and confirm.

### CODE REVIEW

**Comment by Lyncee59** [comment]
Hey @jiagengliu , could you provide me more details to help me verifying those addresses ? The coinbase txs involved don't have any miner details related to Poolin in their sigscript and I could not find any clear link between those reward addresses and the miner addresses in the PR.

Also can you point me any official resource to confirm the Poolin reward distributors addresses you mentionned above?

Cheers

**Comment by AlejandroDeLaTorre** [comment]
any update on this? thanks

**Comment by Lyncee59** [comment]
Hey @jiagengliu , @AlejandroDeLaTorre , we usually don't add batches of payout addresses, its time consuming and difficult to verify. I accept it for this time, but I would strongly advise to enforce using the coinbase_tag in the future! Thanks per advance

**Comment by AlejandroDeLaTorre** [comment]
we appreciate it, thank you

**Pull request merged**
