### PR TITLE
Update pools.json

### PR DESCRIPTION
**Pull request by jinxinslim**
add https://xbtc.exc.com

### CODE REVIEW

**Comment by jameshilliard** [comment]
The website at that URL appears to be down, has this pool mined any blocks so far?

**Comment by jameshilliard** [comment]
Seeing blocks now https://blockchain.info/tx/2d9db0e25769602915f9dd21186f6dd793bd89bf5df48e8ce5599b7884b9ed03

**Comment by jameshilliard** [comment]
@alecalve This should be ready to merge now

**Comment by alecalve** [comment]
Indeed, forgot about it

**Pull request merged**
