### PR TITLE
Add A-XBT company

### PR DESCRIPTION
**Pull request by legkodymov**
Make reference to http://www.a-xbt.com

### CODE REVIEW

**Comment by tuzzolo** [comment]
Can you provide a block height of a block mined by A-XBT?

**Comment by legkodymov** [comment]
373015, 380182, 380083, ...

**Comment by jameshilliard** [comment]
Your coinbase sig in those blocks does not appear to be encoded with the string "axbt", have you fixed that on your stratum server?

**Comment by legkodymov** [comment]
Understood your idea. Didn't know about it. Waiting for new block with signature.

**Comment by jameshilliard** [comment]
The coinbase tag in your latest block is "/A-XBT/" not "axbt". I submitted a corrected pull request [here](https://github.com/blockchain/Blockchain-Known-Pools/pull/66).

**Pull request merged**
